#! /usr/bin/env bash

cd "$(dirname "$0")"
source venv/bin/activate
path=tests
for entry in "$path"/*
    do
      if [[ "$entry" ==  *.py ]]; then
        echo "running $entry..."
        venv/bin/python "$entry"
      fi 
done

